modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/chrrs/scribble/issues"
license = "MIT"

[[mods]]
modId = "scribble"
version = "${version}"
displayName = "Scribble"
description = "Expertly edit your books with rich formatting options, page utilities and more!"
authors = "chrrrs"
credits = "WiskiWiski"
logoFile = "assets/scribble/banner.png"
logoBlur = false

[[mixins]]
config = "scribble.mixins.json"

[[dependencies.scribble]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft}"